using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Data;
using System.Data.SqlClient;

namespace SampleAdo
{
    /// <summary>
    /// Author : CG
    /// DoC: 12th Oct
    /// Desc : To Add and Display Employee details
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class EmpDetails : Window
    {
        public EmpDetails()
        {
            InitializeComponent();
        }

        public static DataTable LoadDataGrid()
        {
            SqlDataReader rdrEmp = null;
            SqlConnection connObj = new SqlConnection();
            DataTable dtEmp = new DataTable();
            // Initialize the Connection object and set the ConnectionString Property
            try
            {

                connObj.ConnectionString = @"Data Source=ndamssql\sqlilearn;Initial Catalog=Sep19CHN;User ID=sqluser;Password=sqluser";

                #region ignore
                /* Initialize the Command object
                // Initialization1
                SqlCommand cmdObj = new SqlCommand();
                cmdObj.CommandText = "select * from [Geetha].[Employee]";
                cmdObj.Connection = connObj;

                //Initialization2
                SqlCommand cmdObj2 = new SqlCommand("select * from [Geetha].[Employee]");
                cmdObj2.Connection = connObj;*/
                #endregion
                //Initialization3

                SqlCommand cmdObj = new SqlCommand("select * from [Geetha].[Employee]", connObj);

                // Execute the Command
                connObj.Open();
                rdrEmp = cmdObj.ExecuteReader();
                if (rdrEmp.HasRows)
                {
                   
                    dtEmp.Load(rdrEmp);
                    // binding UI with data
                }
               
            }
            catch (SqlException se)
            {
                MessageBox.Show("Exception Occurred" + se.Message,"Employee Form");
            }

            finally
            {
                rdrEmp.Close();
                if (connObj.State == ConnectionState.Open)
                    connObj.Close();
            }
            return dtEmp;
        }

        public static int  GetAutoGeneratedId()
        {
            SqlConnection connObj = new SqlConnection(@"Data Source=ndamssql\sqlilearn;Initial Catalog=Sep19CHN;User ID=sqluser;Password=sqluser");
            SqlCommand cmdObj = new SqlCommand("select IDENT_CURRENT('Geetha.Employee')+ident_incr('Geetha.Employee')", connObj);
            connObj.Open();
            object objResult = cmdObj.ExecuteScalar();
            int newEmpId = Convert.ToInt32(objResult);
            connObj.Close();// return single data - obj
            return newEmpId;
            
        }
        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            dg_Emp.ItemsSource = LoadDataGrid().DefaultView ;
            txt_empId.Text = GetAutoGeneratedId().ToString();



        }

        private void btn_addEmp_Click(object sender, RoutedEventArgs e)
        {
            SqlConnection conObj = new SqlConnection(@"Data Source=ndamssql\sqlilearn;Initial Catalog=Sep19CHN;User ID=sqluser;Password=sqluser");
            SqlCommand cmdObj = new SqlCommand("Geetha.usp_AddEmployee",conObj);
            cmdObj.CommandType = CommandType.StoredProcedure;//@eName,@eLoc,@ePh
            cmdObj.Parameters.AddWithValue("@eName", txt_eName.Text);
            cmdObj.Parameters.AddWithValue("@eLoc", txt_eLoc.Text);
            cmdObj.Parameters.AddWithValue("@ePh", txt_ePh.Text);
            conObj.Open();
            int rowsAffected = cmdObj.ExecuteNonQuery(); // 
            conObj.Close();
            if (rowsAffected >= 1) MessageBox.Show("Record Inserted!!");

        }
    }
}
